spring:
  security:
    user:
      name: ${STORAGE_SERVICE_USER_NAME:storage_service_user}
      password: ${STORAGE_SERVICE_USER_PASSWORD:password}
      roles:
        - SERVICE
  servlet:
    multipart:
      max-file-size: 5000KB
      max_request-size: 5000KB
server:
  port: ${SERVER_STORAGE_PORT:8081}