spring:
  security:
    user:
      name: storage_service_user
      password: password
      roles:
        - SERVICE
  servlet:
    multipart:
      max-file-size: 5000KB
      max_request-size: 5000KB
server:
  port: ${SERVER_STORAGE_PORT:8080}